#          YAML Reference Guide: https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
#                YAML Validator: https://ci.appveyor.com/tools/validate-yaml

# Disable automatic builds
# Without this, the following error shows up:
# "Specify a project or solution file. The directory does not contain a project or solution file."
build: off

# Ignore testing a commit if only the README.md file changed
# Or if various strings are found in the commit message: updated readme, update readme, update docs, update version, update appveyor
skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

# PowerShell Gallery API key for publishing an update to the module
# The "secure:" value is the Appveyor encryption of the key
environment:
  NuGetApiKey:
    secure: pzzBHe3dds15o5jYQLKlsuxO3JbV9rkccb1PwKigFP2vfp9vC579E8KSGhR1GQAA
  GitHubKey:
    secure: mhTvr/vsjuMnWB6+KlvCZ7fDxj7riYN6PdXZFGlogv9OL0G2M3K/7OjxiggarWvi

# Install prereqs for build
install:
  - ps: Import-Module -Name ".\src\$($env:APPVEYOR_PROJECT_NAME).psm1" -Force
  - ps: Update-AppveyorBuild -Version "$((Get-ChangelogData).LastVersion)+$($env:APPVEYOR_BUILD_NUMBER)"
  - ps: Install-PackageProvider -Name NuGet -Force | Out-Null
  - ps: Install-Module -Name InvokeBuild -Force
  - ps: Install-Module -Name Pester -Force
  - ps: Install-Module -Name posh-git -Force
  - ps: Install-Module -Name platyPS -Force
  - ps: Install-Module -Name MarkdownToHtml -Force

#build_script:

# Invoke Pester to run all of the unit tests, then save the results into XML in order to populate the AppVeyor tests section
# If any of the tests fail, consider the pipeline failed
test_script:
  - ps: $res = Invoke-Pester -Path ".\test" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubKey):x-oauth-basic@github.com`n"
  - git config --global user.email "376408+natescherer@users.noreply.github.com"
  - git config --global user.name "Nate Scherer"
  - git config --global core.autocrlf true
  - git config --global core.safecrlf false
  - ps: . .\appveyorbuild.ps1

before_deploy:
  -ps: $env:ChangelogData = (($ChangelogData -split "## \[$PublishVersion")[1] -split "`r`n`r`n")[0] -replace "\].*`r`n",""

deploy:
  tag: "v1.0.0"
  description: $(ChangelogData)
  provider: GitHub
  auth_token: $(GitHubKey)
  artifact: out/.*\.zip
  draft: true
  prerelease: false
  #on:
  #  branch: master                 # release from master branch only
  #  appveyor_repo_tag: true        # deploy on tag push only
