parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
  - powershell: |
      Install-Module -Name Pester -Force -SkipPublisherCheck ${{ parameters.moduleInstallOptions }}
      Invoke-Pester
    displayName: Invoke-Pester