strategy:
  matrix:
    Windows:
      imageName: vs2017-win2016
    Ubuntu:
      imageName: ubuntu-16.04
    macOS:
      imageName: macOS-10.13


pool:
  vmImage: $(imageName)

steps:
- powershell: |
    Install-Module -Name Pester -Force -SkipPublisherCheck
    Invoke-Pester
  displayName: Invoke-Pester