parameters:
  name: ''
  vmImage: ''
  moduleInstallOptions: ''
  pwsh: true

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:

  - task: PowerShell@2
    displayName: Environment Details
    inputs:
      pwsh: ${{ parameters.pwsh }}
      targetType: inline
      script: |
        $PSVersionTable
        Write-Host "Build.Repository.Uri = $env:BUILD_REPOSITORY_URI"
        Write-Host "Build.QueuedBy $env:Build_QueuedBy"
        Write-Host "Build.SourceVersionMessage $env:Build_SourceVersionMessage"

  - task: PowerShell@2
    displayName: ErrorActionPreference
    inputs:
      pwsh: ${{ parameters.pwsh }}
      targetType: inline
      script: $ErrorActionPreference = "Stop"

  - task: PowerShell@2
    displayName: Install-Module
    inputs:
      pwsh: ${{ parameters.pwsh }}
      targetType: inline
      script: Install-Module -Name $env:POWERSHELLMODULES.split(",") -Force -SkipPublisherCheck ${{ parameters.moduleInstallOptions }}

  - task: PowerShell@2
    displayName: Invoke-Pester
    inputs:
      pwsh: ${{ parameters.pwsh }}
      targetType: inline
      script: Invoke-Pester