name: $(BuildId)

trigger:
  branches:
    include:
      - master

variables:
  - group: ReleaseSecrets
  - name: PowerShellModules
    value: ChangelogManagement,Pester,platyPS,BuildHelpers,PowerShellGet
  - name: ArtifactToDeploy
    value: windows-latest
  - name: GitName
    value: Nate Scherer
  - name: GitEmail
    value: 376408+natescherer@users.noreply.github.com
  # Warning: All variables below this line will be expanded via Invoke-Expression or $ExecutionContext.InvokeCommand.ExpandString. This means you can use PowerShell environment
  # variables, but there is also a risk of arbitrary code execution. Proceeed with caution.
  - name: LinkPattern
    value: '@{FirstRelease="https://github.com/$env:BUILD_REPOSITORY_NAME/tree/v{CUR}";NormalRelease="https://github.com/$env:BUILD_REPOSITORY_NAME/compare/v{PREV}..v{CUR}";Unreleased="https://github.com/$env:BUILD_REPOSITORY_NAME/compare/v{CUR}..HEAD"}'
  - name: LicenseUri
    value: https://github.com/$env:BUILD_REPOSITORY_NAME/blob/master/LICENSE
  - name: ProjectUri
    value: https://github.com/$env:BUILD_REPOSITORY_NAME
  - name: HelpInfoUri
    value: https://github.com/$env:BUILD_REPOSITORY_NAME


stages:
- stage: Build
  jobs:
  - job: ubuntu_latest
    pool: 
      vmImage: ubuntu-latest
    steps:
    - template: azure-pipelines-build-steps.yml
      parameters:
        tempDir: /tmp
        moduleInstallOptions: -Scope CurrentUser
        artifactName: ubuntu-latest
  - job: macos_latest
    pool: 
      vmImage: macos-latest
    steps:
    - template: azure-pipelines-build-steps.yml
      parameters:
        tempDir: $env:TMPDIR
        artifactName: macos-latest
  - job: windows_latest_w_windows_powershell
    pool: 
      vmImage: windows-latest
    steps:
    - template: azure-pipelines-build-steps.yml
      parameters:
        tempDir: $env:TEMP
        pwsh: false
        artifactName: windows-latest_w_windows_powershell
  - job: windows_latest
    pool: 
      vmImage: windows-latest
    steps:
    - template: azure-pipelines-build-steps.yml
      parameters:
        tempDir: $env:TEMP
        artifactName: windows-latest
- stage: DeployDev
  condition: eq(variables['PrdVersion'], '')
  jobs:
  - deployment: DeployDev
    pool:
      vmImage: windows-latest
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipelines-deploy-steps.yml
            parameters:
              environmentName: DEV
              artifactToDeploy: $(ArtifactToDeploy)
- stage: DeployPrd
  condition: ne(variables['PrdVersion'], '')
  jobs:
  - deployment: DeployPrd
    pool:
      vmImage: windows-latest
    environment: PRD
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipelines-deploy-steps.yml
            parameters:
              environmentName: PRD
              artifactToDeploy: $(ArtifactToDeploy)