trigger:
  paths:
    exclude:
      - docs/*
      - '*.md'
      - .gitignore

variables:
  - group: BuildSecrets
  - name: PowerShellModules
    value: ChangelogManagement,InvokeBuild,Pester,platyPS,MarkdownToHtml,BuildHelpers,PowerShellGet

jobs:
- template: azure-pipelines-build.yml
  parameters:
    name: linux
    vmImage: 'ubuntu-16.04'
    moduleInstallOptions: -Scope CurrentUser

- template: azure-pipelines-build.yml
  parameters:
    name: macos
    vmImage: 'macOS-10.13'

- template: azure-pipelines-build.yml
  parameters:
    name: windows_w_windows_powershell
    vmImage: 'vs2017-win2016'
    pwsh: false

- template: azure-pipelines-build.yml
  parameters:
    name: windows_w_powershell_core
    vmImage: 'vs2017-win2016'