strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

variables:
  GitName: Nate Scherer
  GitEmail: 376408+natescherer@users.noreply.github.com
  PowerShellModules: ChangelogManagement,InvokeBuild,Pester,platyPS,MarkdownToHtml,BuildHelpers,PowerShellGet

pool:
  vmImage: $(imageName)

steps:
- powershell: |
    Install-Module -Name Pester -Force -SkipPublisherCheck
    Invoke-Pester
  displayName: Invoke-Pester