parameters:
  environmentName: ''
  artifactToDeploy: ''

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: ${{ parameters.artifactToDeploy }}
- task: PowerShell@2
  displayName: Set Artifact Path
  inputs:
    targetType: inline
    script: |
      $ArtifactPath = "$env:PIPELINE_WORKSPACE\${{ parameters.artifactToDeploy }}"
      Write-Host "##vso[task.setvariable variable=artifactPath]$ArtifactPath"
- task: PowerShell@2
  displayName: Install-Module
  inputs:
    targetType: inline
    script: Install-Module -Name $env:DEPLOYMODULES.split(",") -Force -SkipPublisherCheck -AllowClobber
- task: PowerShell@2
  displayName: Set Variables
  inputs:
    targetType: inline
    script: |
      $Module = Get-ChildItem -Path "$env:ARTIFACTPATH\src\*.psm1"
      Write-Host "##vso[task.setvariable variable=ModulePath]$($Module.FullName)"
      Write-Host "##vso[task.setvariable variable=ModuleName]$($Module.BaseName)"
      $Manifest = Get-ChildItem -Path "$env:ARTIFACTPATH\src\*.psd1"
      Write-Host "##vso[task.setvariable variable=ManifestPath]$($Manifest.FullName)"
      $ManifestVersion = (Import-PowerShellDataFile $Manifest.FullName).ModuleVersion
      if ("${{ parameters.environmentName }}" -eq "DEV") {
        if ((Get-ChangelogData -Path "$env:ARTIFACTPATH\CHANGELOG.md").Released.Count -gt 0) {
          $ReleaseVersion = (Step-Version $ManifestVersion) + "-alpha" + (Get-Date -Format "yyyyMMddHmm")
        } else {
          $ReleaseVersion = $ManifestVersion + "-alpha" + (Get-Date -Format "yyyyMMddHmm")
        }
      }
      if ("${{ parameters.environmentName }}" -eq "PRD") {
        $ReleaseVersion = $env:PRDVERSION
      }
      Write-Host "##vso[task.setvariable variable=ReleaseVersion]$ReleaseVersion"
- task: PowerShell@2
  displayName: Update Module Info
  inputs:
    targetType: inline
    script: |
      $VersionPrefix = ($env:RELEASEVERSION -split "-")[0]
      $VersionSuffix = ($env:RELEASEVERSION -split "-")[1]

      $FunctionsToExport = @()	
      $PublicFiles = Get-ChildItem -Path "$env:ARTIFACTPATH\src\Public\*.ps1"
      foreach ($PublicFile in $PublicFiles) {
        $FunctionsToExport += [io.path]::GetFileNameWithoutExtension($PublicFile.FullName)
      }

      $ReleaseNotes = ((Get-ChangelogData -Path "$env:ARTIFACTPATH\CHANGELOG.md").Released[0].RawData -replace "^## .*", "").Trim()

      $ManifestNewData = @{
          Path = $env:MANIFESTPATH
          ReleaseNotes = $ReleaseNotes
          ModuleVersion = $VersionPrefix
          FunctionsToExport = $FunctionsToExport
          LicenseUri = $ExecutionContext.InvokeCommand.ExpandString($env:LICENSEURI)
          ProjectUri = $ExecutionContext.InvokeCommand.ExpandString($env:PROJECTURI)
          HelpInfoUri = $ExecutionContext.InvokeCommand.ExpandString($env:HELPINFOURI)
      }

      if ($VersionSuffix) {
          $ManifestNewData += @{Prerelease = $VersionSuffix}
      }

      Update-ModuleManifest @ManifestNewData

      $ManifestNewData = Get-Content $env:MANIFESTPATH
      $ManifestNewData = $ManifestNewData -replace "^CmdletsToExport.*$", "CmdletsToExport = @()" 
      $ManifestNewData = $ManifestNewData -replace "^AliasesToExport.*", "AliasesToExport = @()"
      $ManifestNewData = $ManifestNewData -replace "^VariablesToExport.*", "VariablesToExport = @()"
      Set-Content -Path $env:MANIFESTPATH -Value $ManifestNewData
- task: PowerShell@2
  displayName: Update Changelog
  inputs:
    targetType: inline
    script: |
      if ("${{ parameters.environmentName }}" -eq "DEV") {
        Write-Host -Object "Ignoring changlog as Environment is DEV."
      }
      else {
        $ChangelogData = Get-ChangelogData -Path "$env:ARTIFACTPATH\CHANGELOG.md"
        if (($ChangelogData.Unreleased.Data.Added -eq $null) -and
            ($ChangelogData.Unreleased.Data.Changed -eq $null) -and
            ($ChangelogData.Unreleased.Data.Deprecated -eq $null) -and
            ($ChangelogData.Unreleased.Data.Fixed -eq $null) -and
            ($ChangelogData.Unreleased.Data.Security -eq $null)) {
                throw "Environment is PRD, but no changes are listed in changelog. Exiting."
        }
        $LinkHash = Invoke-Expression $env:LINKPATTERN
        Update-Changelog -ReleaseVersion $env:RELEASEVERSION -LinkMode "Automatic" -LinkPattern $LinkHash -Path "$env:ARTIFACTPATH\CHANGELOG.md"
      }
- task: PowerShell@2
  displayName: Generate Markdown Help Files
  inputs:
    targetType: inline
    script: |
      if (!(Test-Path -Path "$env:ARTIFACTPATH\docs")) {
        New-Item -Path "$env:ARTIFACTPATH\docs" -ItemType Directory | Out-Null
      }
      Get-Module -Name $env:MODULENAME -All | Remove-Module -Force -ErrorAction Ignore
      Import-Module -Name $env:MODULEPATH -Force -ErrorAction Stop
      New-MarkdownHelp -Module $env:MODULENAME -OutputFolder "$env:ARTIFACTPATH\docs" -ErrorAction SilentlyContinue | Out-Null
- task: PowerShell@2
  displayName: Generate HTML Help Files
  inputs:
      targetType: inline
      script: |
        # Set variables used by different platforms
        $NL = [System.Environment]::NewLine

        New-Item -Path "$env:ARTIFACTPATH\out\" -Type Directory -ErrorAction SilentlyContinue | Out-Null
        New-Item -Path "$env:ARTIFACTPATH\out\docs" -Type Directory -ErrorAction SilentlyContinue | Out-Null

        function ConvertTo-HtmlFromMarkdown {
          [CmdletBinding()]
          param(
              [Parameter(Mandatory = $true)]
              # The path of the file to convert
              [string]$Path,
              [Parameter(Mandatory = $true)]
              # The output path for the HTML
              [string]$OutputPath,
              [Parameter(Mandatory = $true)]
              # String containing HTML template
              [string]$Template,
              # String containing title for the HTML
              [string]$Title       
          )
          $Item = Get-Item -Path $Path
          $Content = Get-Content -Path $Path -Raw
          $Converted = (Invoke-WebRequest -Method POST -ContentType "text/plain" -Body $Content -Uri "https://api.github.com/markdown/raw" -UseBasicParsing).Content
          $Html = $Template.Replace("[content]", $Converted)
          $Html = $Html.Replace("[title]", $Title)
          Set-Content -Value $Html -Path $OutputPath -NoNewLine
        }

        # Create template used for HTML conversion
        $MarkdownStyle = (Invoke-WebRequest -Uri "https://raw.githubusercontent.com/sindresorhus/github-markdown-css/gh-pages/github-markdown.css" -UseBasicParsing).Content
        $HtmlTemplate = (Invoke-WebRequest -Uri "https://gist.githubusercontent.com/natescherer/3475c1a0aa5487dd7d5c967553e13ea6/raw/704ed32a04b717a660d561fa4180df14d7ed392a/MarkdownToHtmlTemplate.html" -UseBasicParsing).Content
        $HtmlTemplate = $HtmlTemplate.Replace("[style]", $MarkdownStyle)

        # Convert CHANGELOG.md
        ConvertFrom-Changelog -Path "$env:ARTIFACTPATH\CHANGELOG.md" -Format "Release" -OutputPath "$env:ARTIFACTPATH\CHANGELOG_out.md"
        ConvertTo-HtmlFromMarkdown -Template $HtmlTemplate -Path "$env:ARTIFACTPATH\CHANGELOG_out.md" -OutputPath "$env:ARTIFACTPATH\out\CHANGELOG.html" -Title "CHANGELOG"
        Remove-Item -Path "$env:ARTIFACTPATH\CHANGELOG_out.md"

        # Convert README.md
        ConvertTo-HtmlFromMarkdown -Template $HtmlTemplate -Path "$env:ARTIFACTPATH\README.md" -OutputPath "$env:ARTIFACTPATH\out\README.html" -Title "README"

        # Convert help files
        $MarkdownFiles = Get-ChildItem -Path "$env:ARTIFACTPATH\docs"
        foreach ($File in $MarkdownFiles) {
          $OutputPath = "$env:ARTIFACTPATH\out\docs\" + $File.Name.Replace(".md","") + ".html"
          ConvertTo-HtmlFromMarkdown -Template $HtmlTemplate -Path $File.FullName -OutputPath $OutputPath -Title $File.Name.Replace(".md","")
        }
- task: PowerShell@2
  displayName: Copy 'src' to 'out'
  inputs:
    targetType: inline
    script: Copy-Item -Path "$env:ARTIFACTPATH\src\*" -Destination "$env:ARTIFACTPATH\out\$env:MODULENAME" -Recurse
- task: PowerShell@2
  displayName: (DEV Only) Publish Module to PoshTestGallery
  condition: eq('${{ parameters.environmentName }}', 'DEV')
  env:
    GALLERYKEY: $(PoshTestGalleryKey)
  inputs:
    targetType: inline
    script: |
      $RegisterSplat = @{
        Name = "PoshTestGallery"
        SourceLocation = "https://www.poshtestgallery.com/api/v2"
        PublishLocation = "https://www.poshtestgallery.com/api/v2/package/"
        ScriptSourceLocation = "https://www.poshtestgallery.com/api/v2/items/psscript"
        ScriptPublishLocation = "https://www.poshtestgallery.com/api/v2/package/"
      }
      Register-PSRepository @RegisterSplat
      $PublishSplat = @{
        Repository = "PoshTestGallery"
        Path = "$env:ARTIFACTPATH\out\$env:MODULENAME"
        NuGetApiKey = $env:GALLERYKEY
        ErrorAction = "Stop"
      }
      Publish-Module @PublishSplat
- task: PowerShell@2
  displayName: (PRD Only) Compress module for GitHub release
  condition: eq('${{ parameters.environmentName }}', 'PRD')
  inputs:
    targetType: inline
    script: Compress-Archive -Path "out\$env:MODULENAME" -DestinationPath "$env:ARTIFACTPATH\out\$env:MODULENAME-v$env:RELEASEVERSION.zip"
- task: PowerShell@2
  displayName: (PRD Only) Publish GitHub release
  condition: eq('${{ parameters.environmentName }}', 'PRD')
  inputs:
    targetType: inline
    script: |
      $Zip = Get-ChildItem "$env:ARTIFACTPATH\out\$env:MODULENAME-v$env:RELEASEVERSION.zip"
      $ManifestData = Import-PowerShellDataFile "$env:ARTIFACTPATH\src\*.psd1"
      $GitHubUser = $env:BUILD_REPOSITORY_NAME.split("/")[0]
      $AuthHeader = "Basic {0}" -f [System.Convert]::ToBase64String([char[]]"$GitHubUser`:$env:GITHUBPAT")
      $ReleaseFilePath = $Zip.FullName
      $ReleaseFileName = Split-Path -Path $ReleaseFilePath -Leaf
      $ReleaseVersion = $env:RELEASEVERSION
      $ReleaseBody = $ManifestData.PrivateData.PSData.ReleaseNotes

      $ReleaseParams = @{
          Headers = @{
              "Authorization" = $AuthHeader
          }
          Body = ConvertTo-Json -InputObject @{
              tag_name = "v$env:RELEASEVERSION"
              name = "v$env:RELEASEVERSION"
              body = $ReleaseBody
          }
          Uri = "https://api.github.com/repos/$env:BUILD_REPOSITORY_NAME/releases"
          Method = "Post"
      }
      $ReleaseResult = Invoke-RestMethod @ReleaseParams

      if ($ReleaseResult.upload_url) {
        $UploadParams = @{
            Headers = @{
                Authorization = $AuthHeader
                Content-Type = "application/zip"
            }
            Uri = $ReleaseResult.upload_url.split("{")[0] + "?name=$ReleaseFileName"
            Method = "Post"
            InFile = $Zip.FullName
        }
        $UploadResult = Invoke-RestMethod @UploadParams

        if ($UploadResult.state -ne "uploaded") {
            Write-Output $UploadResult
            throw "There was a problem uploading."
        }
      }
      else {
          Write-Output $ReleaseResult
          throw "There was a problem releasing."
      }
- task: PowerShell@2
  displayName: (PRD Only) Publish Module to PowerShellGallery
  condition: eq('${{ parameters.environmentName }}', 'PRD')
  env:
    GALLERYKEY: $(PSGalleryKey)
  inputs:
    targetType: inline
    script: |
      $PublishSplat = @{
        Path = "$env:ARTIFACTPATH\out\$env:MODULENAME"
        NuGetApiKey = $env:GALLERYKEY
        ErrorAction = "Stop"
      }
      Publish-Module @PublishSplat
- checkout: self
  displayName: (PRD Only) Git checkout
  condition: eq('${{ parameters.environmentName }}', 'PRD')
  path: pushback
  persistCredentials: true
- task: CopyFiles@2
  displayName: (PRD Only) Copy files to git directory
  condition: eq('${{ parameters.environmentName }}', 'PRD')
  inputs:
    sourceFolder: $(Pipeline.Workspace)\artifact
    targetFolder: $(Agent.BuildDirectory)\pushback
    overWrite: true
- task: Bash@3
  displayName: (PRD Only) Push changes to repo
  condition: eq('${{ parameters.environmentName }}', 'PRD')
  inputs:
    workingDirectory: $(Agent.BuildDirectory)\pushback
    failOnStderr: true
    targetType: inline
    script: |
      git config user.email "$(GitEmail)"
      git config user.name "$(GitName)"
      git add --all
      git commit -m "Azure DevOps Release $(ReleaseVersion) [skip ci]"
      git tag v$(ReleaseVersion)
      git push origin HEAD:master --porcelain
      git push origin --tags --porcelain