name: $(BuildId)

trigger:
  branches:
    include:
      - master

variables:
  BuildModules: Pester,BuildHelpers
  DeployModules: ChangelogManagement,platyPS,BuildHelpers
  ArtifactToDeploy: windows-latest
  GitName: Nate Scherer
  GitEmail: 376408+natescherer@users.noreply.github.com
  # Warning: All variables below this line will be expanded via Invoke-Expression or $ExecutionContext.InvokeCommand.ExpandString. This means you can use PowerShell environment
  # variables, but there is also a risk of arbitrary code execution. Proceeed with caution.
  LinkPattern: '@{FirstRelease="https://github.com/$env:BUILD_REPOSITORY_NAME/tree/v{CUR}";NormalRelease="https://github.com/$env:BUILD_REPOSITORY_NAME/compare/v{PREV}..v{CUR}";Unreleased="https://github.com/$env:BUILD_REPOSITORY_NAME/compare/v{CUR}..HEAD"}'
  LicenseUri: https://github.com/$env:BUILD_REPOSITORY_NAME/blob/master/LICENSE
  ProjectUri: https://github.com/$env:BUILD_REPOSITORY_NAME
  HelpInfoUri: https://github.com/$env:BUILD_REPOSITORY_NAME

stages:
- stage: Build
  jobs:
  - job: ubuntu_latest
    pool: 
      vmImage: ubuntu-latest
    steps:
    - template: azure-pipelines-build-steps.yml
      parameters:
        artifactName: ubuntu-latest
  - job: macos_latest
    pool: 
      vmImage: macos-latest
    steps:
    - template: azure-pipelines-build-steps.yml
      parameters:
        artifactName: macos-latest
  - job: windows_latest_w_windows_powershell
    pool: 
      vmImage: windows-latest
    steps:
    - template: azure-pipelines-build-steps.yml
      parameters:
        pwsh: false
        artifactName: windows-latest_w_windows_powershell
  - job: windows_latest
    pool: 
      vmImage: windows-latest
    steps:
    - template: azure-pipelines-build-steps.yml
      parameters:
        artifactName: windows-latest
- stage: DeployDev
  condition: eq(variables['PrdVersion'], '')
  variables:
    - group: ReleaseSecrets
  jobs:
  - deployment: DeployDev
    pool:
      vmImage: windows-latest
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipelines-deploy-steps.yml
            parameters:
              environmentName: DEV
              artifactToDeploy: $(ArtifactToDeploy)
- stage: DeployPrd
  condition: ne(variables['PrdVersion'], '')
  variables:
    - group: ReleaseSecrets
  jobs:
  - deployment: DeployPrd
    pool:
      vmImage: windows-latest
    environment: PRD
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipelines-deploy-steps.yml
            parameters:
              environmentName: PRD
              artifactToDeploy: $(ArtifactToDeploy)