name: CI
on: 
  push:
    paths-ignore:
    - '**.md'
    - '**.yml'
  workflow_dispatch:
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        shell: [pwsh, powershell]
        exclude:
          - os: ubuntu-latest
            shell: powershell
          - os: macos-latest
            shell: powershell
    steps:
      - name: Set Variables
        run: |
          "BARE_REPOSITORY=$($env:GITHUB_REPOSITORY.split("/")[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Pester Tests
        id: pester
        uses: zyborg/pester-tests-report@v1
        with:
          skip_check_run: true
          report_name: TestResults_${{ runner.os }}_${{ matrix.shell }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: ${{ env.BARE_REPOSITORY }}_TestResults_${{ runner.os }}_${{ matrix.shell }}.md
          gist_badge_label: ${{ runner.os }} ${{ matrix.shell }}
          gist_token: ${{ secrets.PESTER_GIST_TOKEN }}
          tests_fail_step: true
          coverage_paths: src\private,src\public
          coverage_report_name: CoverageResults_${{ runner.os }}_${{ matrix.shell }}
          coverage_gist: true
          coverage_gist_badge_label: Code Coverage
      # - name: Convert Path for Codecov Action
      #   run: |
      #     if [[ "${{ matrix.os }}" -eq "windows-latest" ]] 
      #     then
      #       echo "CODE_COVERAGE_PATH=$(cygpath -u '${{ steps.pester.outputs.coverage_results_path }}')" >> $GITHUB_ENV
      #     else
      #       echo "CODE_COVERAGE_PATH=${{ steps.pester.outputs.coverage_results_path }}" >> $GITHUB_ENV
      #     fi
      #   shell: bash
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ${{ steps.pester.outputs.coverage_results_path }}
          fail_ci_if_error: true